# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-18 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='state_field',
            new_name='state',
        ),
    ]
